<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * AI pricing engine (Phase 5, built on claude-opus-4-8).
 *
 * pricing_rules — base/per-mile/per-minute rates and time-of-day / demand
 *   multipliers per vehicle type.
 * bank_holidays — dates that attract a surcharge.
 * quotes — generated quotes (AI or rule-based) with the inputs and the price,
 *   so a quote can convert to a confirmed booking in under 60 seconds.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('pricing_rules', function (Blueprint $table) {
            $table->id();
            $table->foreignId('vehicle_type_id')->constrained()->cascadeOnDelete();
            $table->decimal('base_fare', 8, 2)->default(0);
            $table->decimal('per_mile', 8, 2)->default(0);
            $table->decimal('per_minute', 8, 2)->default(0);
            $table->decimal('minimum_fare', 8, 2)->default(0);
            $table->decimal('airport_surcharge', 8, 2)->default(0);
            $table->decimal('night_multiplier', 5, 2)->default(1)->comment('Applied to time-of-day band');
            $table->time('night_starts_at')->nullable();
            $table->time('night_ends_at')->nullable();
            $table->decimal('peak_multiplier', 5, 2)->default(1);
            $table->boolean('is_active')->default(true);
            $table->timestamps();

            $table->index(['vehicle_type_id', 'is_active']);
        });

        Schema::create('bank_holidays', function (Blueprint $table) {
            $table->id();
            $table->date('date')->unique();
            $table->string('name');
            $table->decimal('surcharge_percent', 5, 2)->default(0);
            $table->timestamps();
        });

        Schema::create('quotes', function (Blueprint $table) {
            $table->id();
            $table->string('reference', 24)->unique();
            $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('vehicle_type_id')->constrained()->cascadeOnUpdate()->restrictOnDelete();
            $table->text('pickup_address');
            $table->text('destination_address');
            $table->decimal('distance_miles', 8, 2)->nullable();
            $table->unsignedInteger('duration_minutes')->nullable();
            $table->dateTime('pickup_at')->nullable();
            $table->decimal('price', 10, 2);
            $table->boolean('ai_generated')->default(false)->comment('Generated by claude-opus-4-8');
            $table->json('breakdown')->nullable();
            $table->foreignId('converted_booking_id')->nullable()->constrained('bookings')->nullOnDelete();
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();

            $table->index('reference');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('quotes');
        Schema::dropIfExists('bank_holidays');
        Schema::dropIfExists('pricing_rules');
    }
};
